name: 'USN Monitor'

description: |
  Monitors for new USNS and adds them to main USN list.
inputs:
  build_receipt:
    description: 'Path to build receipt'
    required: true
  run_receipt:
    description: 'Path to run receipt'
    required: true
  full_usn_list:
    description: 'Path to full USN list'
    required: true
  relevant_usn_list:
    description: 'Path to relevant USN list'
    required: true

runs:
  using: 'composite'
  steps:
  - id: release-notes
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail

      pushd "${{ github.action_path }}/usn-recorder" >/dev/null
        go build -o usn-recorder .
      popd >/dev/null

      "${{ github.action_path }}/usn-recorder/usn-recorder" \
        --build-receipt "${{ inputs.build_receipt }}" \
        --run-receipt "${{ inputs.run_receipt }}" \
        --full-usn-list "${{ inputs.full_usn_list }}" \
        --relevant-usn-list "${{ inputs.relevant_usn_list }}"

      rm -f "${{ github.action_path }}/usn-recorder/usn-recorder"
