name: 'Generate Receipt Diffs'

description: |
  Generate receipt diffs for a stack

outputs:
  run_diff:
    description: Run receipt diff
    value: ${{ steps.receipt-diff.outputs.run_diff }}
  build_diff:
    description: Build receipt diff
    value: ${{ steps.receipt-diff.outputs.build_diff }}

inputs:
  repo:
    description: 'Repository that will have draft release reset'
    required: true
  user:
    description: 'User for private repositories'
    required: false
  token:
    description: 'Token for private repositories'
    required: false

runs:
  using: 'composite'
  steps:
  - id: receipt-diff
    shell: bash
    run: |
      #!/usr/bin/env bash
      set -euo pipefail

      ${{ github.action_path }}/generate-diffs \
        "${{ inputs.user }}" \
        "${{ inputs.token }}" \
        "${{ inputs.repo }}"
