name: Test USN Patch
on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/test-usn-patch.yml'
    - 'actions/usn-patch/entrypoint/**'

jobs:
  test-usn-patch:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Run Tests
      run: |
        cd actions/usn-patch/entrypoint
        go test ./...

  approve:
    name: Auto Approve
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    needs: test-usn-patch
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Approve
      uses: paketo-buildpacks/github-config/actions/pull-request/approve@main
      with:
        token: ${{ secrets.PAKETO_BOT_REVIEWER_GITHUB_TOKEN }}
        number: ${{ github.event.number }}
